name: 'Setup Coni Compiler'
description: 'Downloads and installs the Coni compiler'
runs:
  using: "composite"
  steps:
    - name: Download Coni Compiler
      shell: bash
      run: |
        git clone https://gitea.hellonico.info/hellonico/coni-lang.git $GITHUB_WORKSPACE/../coni-lang
        cd $GITHUB_WORKSPACE/../coni-lang
        CGO_ENABLED=0 go build -o coni .
        chmod +x coni
        mkdir -p $GITHUB_WORKSPACE/bin
        mv coni $GITHUB_WORKSPACE/bin/coni
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
        echo "CONI_HOME=$GITHUB_WORKSPACE/../coni-lang" >> $GITHUB_ENV
