name: 'Setup Coni Compiler'
description: 'Downloads and installs the Coni compiler'
runs:
  using: "composite"
  steps:
    - name: Download Coni Compiler
      shell: bash
      run: |
        git clone https://gitea.hellonico.info/hellonico/coni-lang.git /tmp/coni-lang-src
        cd /tmp/coni-lang-src
        CGO_ENABLED=0 go build -o coni .
        chmod +x coni
        mkdir -p $GITHUB_WORKSPACE/bin
        mv coni $GITHUB_WORKSPACE/bin/coni
        echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
