- name: Demonstrate Variable Loading
  hosts: all
  tasks:
    - name: Show Variables
      debug:
        msg: |
          Global Application Version: {{ app_version }}
          Global Database Port: {{ db_port }}
          Host HTTP Port: {{ http_port }}
          Host Name: {{ inventory_hostname }}
