tasks:
  - name: Clone a repository natively
    git:
      repo: "https://github.com/torvalds/test-tlb.git"
      dest: "tmp/test-tlb-native"

  - name: Download a zip file
    get_url:
      url: "https://github.com/torvalds/test-tlb/archive/refs/heads/master.zip"
      dest: "tmp/test.zip"

  - name: Unzip the downloaded zip natively
    unzip:
      src: "tmp/test.zip"
      dest: "tmp/unzipped"

  - name: Finishing up
    debug:
      msg: "Native git and unzip tasks finished successfully!"
